'use client';
import { usePathname } from 'next/navigation';
import Link from 'next/link';
import Image from 'next/image';
import { treatmentLanguages } from '@/content/treatment-languages';
import { clinic, addressText } from '@/config/clinic';
import { languages, type Language } from '@/content/languages';
const menuLabels = { en: 'Menu', zh: '菜单', vi: 'Menu', mn: 'Цэс', ne: 'मेनु', ru: 'Меню', uz: 'Menyu', th: 'เมนู' };
const kakaoLabels = { en: 'Chat on KakaoTalk', zh: 'KakaoTalk 咨询', vi: 'Tư vấn KakaoTalk', mn: 'KakaoTalk зөвлөгөө', ne: 'KakaoTalk परामर्श', ru: 'Чат в KakaoTalk', uz: 'KakaoTalk orqali maslahat', th: 'แชท KakaoTalk' };
function KakaoContact({label='카카오톡 상담'}:{label?:string}) { return clinic.kakaoURL ? <a className="button kakao" href={clinic.kakaoURL}>{label}</a> : null; }
const bookingLabels = { en: 'Book on Naver', zh: 'Naver 预约', vi: 'Đặt lịch Naver', mn: 'Naver цаг захиалах', ne: 'Naver मा बुकिङ', ru: 'Запись через Naver', uz: 'Naver orqali yozilish', th: 'จองผ่าน Naver' };
function NaverBooking({label='네이버 예약'}:{label?:string}) { return clinic.reservationURL ? <a className="button naver" href={clinic.reservationURL} target="_blank" rel="noopener noreferrer">{label}</a> : null; }
function useGuide() { const pathname = usePathname(); const code = pathname.split('/')[2]; return pathname.startsWith('/guide/') && Object.hasOwn(languages, code) ? { code: code as Language, text: languages[code as Language] } : null; }
export function Brand() { return <Link href="/" className="brand" aria-label={`${clinic.name} 홈`}><span className="brand-symbol" aria-hidden="true">H</span><span>{clinic.name}<small>YEONSU HAPPY DENTAL</small></span></Link>; }
const nav = [['/about','병원 소개'],['/dentist','의료진'],['/treatments','진료 안내'],['/location','오시는 길']];
const flagArt: Record<string,string> = {
  en: '<rect width="60" height="40" fill="white"/><path stroke="#b22234" stroke-width="3.077" d="M0 1.538h60M0 7.692h60M0 13.846h60M0 20h60M0 26.154h60M0 32.308h60M0 38.462h60"/><rect width="24" height="21.538" fill="#3c3b6e"/><defs><path id="us-star" d="m0-1.1.25.76h.8L.4.13l.25.76L0 .42l-.65.47.25-.76-.65-.47h.8z" fill="white"/><g id="us-six"><use href="#us-star" x="2"/><use href="#us-star" x="6"/><use href="#us-star" x="10"/><use href="#us-star" x="14"/><use href="#us-star" x="18"/><use href="#us-star" x="22"/></g><g id="us-five"><use href="#us-star" x="4"/><use href="#us-star" x="8"/><use href="#us-star" x="12"/><use href="#us-star" x="16"/><use href="#us-star" x="20"/></g></defs><use href="#us-six" y="2.15"/><use href="#us-five" y="4.31"/><use href="#us-six" y="6.46"/><use href="#us-five" y="8.62"/><use href="#us-six" y="10.77"/><use href="#us-five" y="12.92"/><use href="#us-six" y="15.08"/><use href="#us-five" y="17.23"/><use href="#us-six" y="19.38"/>',
  ko: '<rect width="60" height="40" fill="white"/><circle cx="30" cy="20" r="10" fill="#cd2e3a"/><path d="M20 20a10 10 0 0 0 20 0 5 5 0 0 0-10 0 5 5 0 0 1-10 0" fill="#0047a0"/><g stroke="#111" stroke-width="2"><path d="M8 7l8 6m-10-3l8 6m-10-3l8 6M44 27l3 2m2 2l3 2m-10-3l3 2m2 2l3 2m-10-3l3 2m2 2l3 2M44 13l8-6m-10 3l3-2m2-2l3-2m-10 3l8-6M8 27l3-2m2-2l3-2m-10 9l8-6m-10 9l3-2m2-2l3-2"/></g>',
  zh: '<rect width="60" height="40" fill="#de2910"/><g fill="#ffde00"><path d="m10 5 1.5 4.5H16l-3.6 2.6 1.4 4.4-3.8-2.7-3.8 2.7 1.4-4.4L4 9.5h4.5z"/><path d="m20 3 .6 1.8h1.9L21 6l.6 1.8L20 6.7l-1.6 1.1L19 6l-1.5-1.2h1.9z" id="star"/><use href="#star" x="4" y="5"/><use href="#star" x="4" y="11"/><use href="#star" y="16"/></g>',
  vi: '<rect width="60" height="40" fill="#da251d"/><path d="m30 7 3.2 9.5h10l-8.1 5.9 3.1 9.6-8.2-6-8.2 6 3.1-9.6-8.1-5.9h10z" fill="#ff0"/>',
  mn: '<path fill="#da2032" d="M0 0h60v40H0z"/><path fill="#0066b3" d="M20 0h20v40H20z"/><g fill="#ffdf00"><path d="M9 7l1-3 1 3 1 2H8zM6 18h2v15H6zm6 0h2v15h-2zM8 18h4v2H8zm0 11h4v2H8zm0-8h4v7H8zM8 16l2 2 2-2zm0 17 2 2 2-2z"/><circle cx="10" cy="12" r="3"/></g>',
  ne: '<path d="M12 2v36h33L28 22h14z" fill="#003893"/><path d="M14 6v30h26L24 20h12z" fill="#dc143c"/><g fill="white"><path d="M17 14q6 7 12 0-6 3-12 0"/><path d="m22 24 1 3 3-1-1 3 3 1-3 1 1 3-3-1-1 3-1-3-3 1 1-3-3-1 3-1-1-3 3 1z"/></g>',
  ru: '<path fill="white" d="M0 0h60v40H0z"/><path fill="#0039a6" d="M0 13.33h60v13.34H0z"/><path fill="#d52b1e" d="M0 26.67h60V40H0z"/>',
  uz: '<path fill="#0099b5" d="M0 0h60v40H0z"/><path fill="#ce1126" d="M0 12h60v16H0z"/><path fill="white" d="M0 14h60v12H0z"/><path fill="#1eb53a" d="M0 28h60v12H0z"/><circle cx="9" cy="6" r="4" fill="white"/><circle cx="11" cy="5" r="3.5" fill="#0099b5"/><g fill="white"><path d="M18 3h1v1h-1zm4 0h1v1h-1zm4 0h1v1h-1zM16 6h1v1h-1zm4 0h1v1h-1zm4 0h1v1h-1zm4 0h1v1h-1zM14 9h1v1h-1zm4 0h1v1h-1zm4 0h1v1h-1zm4 0h1v1h-1zm4 0h1v1h-1z"/></g>',
  th: '<path fill="#a51931" d="M0 0h60v40H0z"/><path fill="white" d="M0 6.67h60v26.66H0z"/><path fill="#2d2a4a" d="M0 13.33h60v13.34H0z"/>',
};
function LanguageFlag({code}:{code:string}) { return flagArt[code] ? <svg aria-hidden="true" width="30" height="20" viewBox="0 0 60 40" style={{verticalAlign:'middle',marginRight:7,flexShrink:0}} dangerouslySetInnerHTML={{__html:flagArt[code]}}/> : null; }
export function Header() {
  const guide = useGuide();
  const links = guide ? [[`/guide/${guide.code}/#guide-treatments`, treatmentLanguages[guide.code].menu], [`/guide/${guide.code}/#guide-hours`, guide.text.hours], [`/guide/${guide.code}/#guide-location`, guide.text.directions], [`/guide/${guide.code}/#guide-before`, guide.text.appointment]] : nav;
  const menu = guide ? menuLabels[guide.code] : '메뉴';
  return <header className="header" lang={guide?.text.lang || 'ko'}><nav className="language-nav container" aria-label="언어 선택 / Language"><Link href="/" lang="ko"><LanguageFlag code="ko"/>한국어</Link>{Object.entries(languages).map(([code, text]) => <Link key={code} href={`/guide/${code}/`} lang={text.lang} aria-current={guide?.code === code ? 'page' : undefined}><LanguageFlag code={code}/>{text.label}</Link>)}</nav><div className="container header-inner"><Brand/><nav className="desktop-nav" aria-label={menu}>{links.map(([url,name])=><Link key={url} href={url}>{name}</Link>)}</nav><details className="mobile-menu" key={guide?.code || 'ko'}><summary>{menu}</summary><nav aria-label={menu}>{links.map(([url,name])=><Link key={url} href={url}>{name}</Link>)}</nav></details></div></header>;
}
export function Hours() { return <div className="hours-list">{clinic.hours.map(h=><div key={h.label}><span>{h.label}</span><strong>{h.open}<span className="dash">–</span>{h.close}</strong></div>)}</div>; }
export function ContactActions() { return <div className="actions"><Link className="button" href="/treatments">진료 안내</Link><a className="button secondary" href="/location/#location-map">오시는 길</a>{clinic.phone ? <a className="button secondary" href={`tel:${clinic.phone.replace(/[^\d+]/g,'')}`}>전화하기</a> : <span className="button inactive" aria-disabled="true">전화 연결 준비 중</span>}<NaverBooking/><KakaoContact/></div>; }
export function Photo({kind='hero'}:{kind?:'hero'|'doctor'}) { return <div className={`photo photo-${kind}`} style={kind === 'doctor' ? { aspectRatio: '3 / 4', height: 'auto' } : undefined}><Image style={{ objectFit: 'cover', objectPosition: 'center top' }} src={clinic.photos[kind]} alt={kind==='hero'?'병원 실제 사진 등록 예정':'양세기 원장'} fill sizes={kind==='hero'?'(max-width: 760px) 100vw, 50vw':'(max-width: 760px) 100vw, 35vw'} priority={kind==='hero'}/></div>; }
export function Footer() {
  const guide = useGuide();
  if (guide) return <><footer className="footer" lang={guide.text.lang}><div className="container footer-grid"><Brand/><div><strong>{guide.text.address}</strong><p>{guide.text.doctor}</p><a href={`tel:${clinic.phone}`}>{clinic.phone}</a><p><NaverBooking label={bookingLabels[guide.code]}/></p><p><KakaoContact label={kakaoLabels[guide.code]}/></p><p><Link href="/">{guide.text.home}</Link></p></div></div><div className="container footer-bottom">© {clinic.name}</div></footer><nav className="mobile-actions" lang={guide.text.lang} aria-label={menuLabels[guide.code]}><a href={`tel:${clinic.phone}`}>{guide.text.call}</a><NaverBooking label={bookingLabels[guide.code]}/><KakaoContact label={kakaoLabels[guide.code]}/><a href={clinic.googleDirectionsURL}>{guide.text.directions}</a></nav></>;
  return <><footer className="footer"><div className="container footer-grid"><Brand/><div><strong>{addressText}</strong><p>원장 {clinic.doctorName} · <a href={`tel:${clinic.phone.replace(/[^\d+]/g,'')}`}>{clinic.phone}</a> · 오시는 길: {clinic.directionsLabel}</p><p><NaverBooking/></p><p><KakaoContact/></p><Link href="/privacy">개인정보처리방침</Link> · <Link href="/information">치과정보</Link></div></div><div className="container footer-bottom">© {clinic.name}<span>현재 사이트는 병원 정보 및 콘텐츠 검토 전 초안입니다.</span></div></footer><nav className="mobile-actions" aria-label="빠른 이용">{clinic.phone?<a href={`tel:${clinic.phone}`}>전화하기</a>:<span aria-disabled="true">전화 준비 중</span>}<NaverBooking/><KakaoContact/><a href={clinic.googleDirectionsURL}>오시는 길</a></nav></>;
}
export function Breadcrumb({title, parent}:{title:string,parent?:{name:string,url:string}}) { return <nav className="breadcrumb" aria-label="현재 위치"><Link href="/">홈</Link><span>/</span>{parent&&<><Link href={parent.url}>{parent.name}</Link><span>/</span></>}<span aria-current="page">{title}</span></nav>; }
export function PageIntro({eyebrow,title,description}:{eyebrow:string,title:string,description:string}) {return <div className="page-intro"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>;}
export function Notice({children}:{children:React.ReactNode}) { return <div className="notice">{children}</div>; }



