import Link from 'next/link';
import Image from 'next/image';
import { clinic, addressText } from '@/config/clinic';
import { languages } from '@/content/languages';
export function Brand() { return <Link href="/" className="brand" aria-label={`${clinic.name} 홈`}><span className="brand-symbol" aria-hidden="true">H</span><span>{clinic.name}<small>YEONSU HAPPY DENTAL</small></span></Link>; }
const nav = [['/about','병원 소개'],['/dentist','의료진'],['/treatments','진료 안내'],['/faq','자주 묻는 질문'],['/location','오시는 길']];
export function Header() { return <header className="header"><nav className="language-nav container" aria-label="언어 선택 / Language"><Link href="/" lang="ko">한국어</Link>{Object.entries(languages).map(([code, text]) => <Link key={code} href={`/guide/${code}/`} lang={text.lang}>{text.label}</Link>)}</nav><div className="container header-inner"><Brand/><nav className="desktop-nav" aria-label="주 메뉴">{nav.map(([url,name])=><Link key={url} href={url}>{name}</Link>)}</nav><details className="mobile-menu"><summary>메뉴</summary><nav aria-label="모바일 주 메뉴">{nav.map(([url,name])=><Link key={url} href={url}>{name}</Link>)}</nav></details></div></header>; }
export function Hours() { return <div className="hours-list">{clinic.hours.map(h=><div key={h.label}><span>{h.label}</span><strong>{h.open}<span className="dash">–</span>{h.close}</strong></div>)}</div>; }
export function ContactActions() { return <div className="actions"><Link className="button" href="/treatments">진료 안내</Link><Link className="button secondary" href="/location">오시는 길</Link>{clinic.phone ? <a className="button secondary" href={`tel:${clinic.phone.replace(/[^\d+]/g,'')}`}>전화하기</a> : <span className="button inactive" aria-disabled="true">전화 연결 준비 중</span>}{clinic.reservationURL ? <a className="button secondary" href={clinic.reservationURL}>상담·예약</a> : <span className="button inactive" aria-disabled="true">예약 연결 준비 중</span>}</div>; }
export function Photo({kind='hero'}:{kind?:'hero'|'doctor'}) { return <div className={`photo photo-${kind}`}><Image src={clinic.photos[kind]} alt={kind==='hero'?'병원 실제 사진 등록 예정':'양세기 원장 사진 등록 예정'} fill sizes={kind==='hero'?'(max-width: 760px) 100vw, 50vw':'(max-width: 760px) 100vw, 35vw'} priority={kind==='hero'}/></div>; }
export function Footer() { return <><footer className="footer"><div className="container footer-grid"><Brand/><div><strong>{addressText}</strong><p>원장 {clinic.doctorName} · <a href={`tel:${clinic.phone.replace(/[^\d+]/g,'')}`}>{clinic.phone}</a> · 오시는 길: {clinic.directionsLabel}</p><Link href="/privacy">개인정보처리방침</Link> · <Link href="/information">치과정보</Link></div></div><div className="container footer-bottom">© {clinic.name}<span>현재 사이트는 병원 정보 및 콘텐츠 검토 전 초안입니다.</span></div></footer><nav className="mobile-actions" aria-label="빠른 이용">{clinic.phone?<a href={`tel:${clinic.phone}`}>전화하기</a>:<span aria-disabled="true">전화 준비 중</span>}{clinic.reservationURL?<a href={clinic.reservationURL}>상담·예약</a>:<span aria-disabled="true">예약 준비 중</span>}<Link href="/location">오시는 길</Link></nav></>; }
export function Breadcrumb({title, parent}:{title:string,parent?:{name:string,url:string}}) { return <nav className="breadcrumb" aria-label="현재 위치"><Link href="/">홈</Link><span>/</span>{parent&&<><Link href={parent.url}>{parent.name}</Link><span>/</span></>}<span aria-current="page">{title}</span></nav>; }
export function PageIntro({eyebrow,title,description}:{eyebrow:string,title:string,description:string}) {return <div className="page-intro"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>;}
export function Notice({children}:{children:React.ReactNode}) { return <div className="notice">{children}</div>; }
