import type {MedicalTranslations} from './types';
export const en: MedicalTranslations = {
 'implant':{
 definition:'Dental implants replace missing teeth by placing an artificial root (fixture) in the jawbone and attaching a connecting component and a restoration.',
 examination:'We review medical conditions, medicines, smoking and oral hygiene. Gum and bite examinations and any necessary imaging assess bone volume and shape, the nerve canal and the maxillary sinus.',
 steps:['Health and oral examination','Plan placement position and timing','Extraction or bone grafting if needed','Implant placement','Check healing and integration','Fit the restoration','Regular maintenance'],
 sections:[{title:'Timing and method of placement',text:'Infection at the extraction site, remaining bone, gums and the possibility of initial stability affect the plan. Examination determines whether placement at extraction or after healing is appropriate.'},{title:'Bone grafting and sinus-related surgery',text:'A bone graft may be considered when bone is insufficient. In the upper back jaw, the relationship between the sinus and remaining bone may require additional surgery. Neither procedure is necessary for every implant.'},{title:'Removal, replacement and revision surgery',text:'Inflammation, bone loss, positioning and fixture fracture are assessed. We consider whether the existing implant can be retained, whether removal is needed, infection control and the timing of replacement. Additional grafting or other replacement options may be discussed.'},{title:'Placement with a digital guide',text:'CT and oral information help assess advance planning and the suitability of a surgical guide. A guide does not replace every incision or additional procedure.'}],
 care:'Keep the surrounding gums clean and follow the eating and hygiene instructions during healing. Regular checks remain necessary after fitting the restoration.',
 caution:'Infection, bleeding, nerve or sinus complications and failure to integrate can occur. Treatment time and the possibility of revision depend on individual health and healing.'},
 'digital-guided-implant':{
 definition:'Imaging and oral information are combined to plan implant position and direction. A surgical guide is made to help apply that plan during surgery.',
 examination:'We check bone, gum thickness and shape, mouth opening, existing teeth and the restoration plan. Agreement between imaging and oral information, guide support and fit are also reviewed.',
 steps:['CT imaging','Obtain oral information','Digital placement planning','Make the surgical guide','Check guide fit','Place the implant using the guide'],
 sections:[{title:'Planning also considers the final tooth',text:'The final tooth position, bite and surrounding structures matter as well as bone volume. The treatment plan or surgical method may need adjustment.'},{title:'Flapless surgery requires a separate assessment',text:'Bone and gum conditions and the need for grafting may require an incision or additional procedures. Using a guide does not mean flapless surgery is possible for every patient.'}],
 care:'Hygiene and follow-up after surgery are as important as with conventional implant placement.',caution:'Imaging and guide inaccuracies, guide fit and findings during surgery must be considered. A guide supports diagnosis and clinical judgment.'},
 'implant-repair':{
 definition:'A loose implant or detached restoration can have different causes. Examination distinguishes problems in the restoration, screw, abutment or fixture within the bone.',
 examination:'We review the implant system and previous records and examine fixation, screws, bite, gums and bone. Removing the restoration or imaging may be necessary.',
 steps:['Review symptoms and previous treatment','Examine components and surrounding tissue','Assess retention and repair options','Retighten, repair, replace or provide further treatment','Check bite and stability','Monitor recurrence'],
 sections:[{title:'“My implant is loose” · “The screw keeps loosening”',text:'Screw or abutment loosening, restoration connection problems and movement of the fixture itself are distinguished. Even when retightening is considered, repeated loosening and bite forces need investigation.',items:['Assess screws and connections','Consider retightening with compatible components and tools','Check abutment and restoration fit']},{title:'“The implant screw broke”',text:'Screw fracture, abutment fracture and fixture wall damage/fracture are different problems. Removal of fragments, damage to the internal connection and the condition of remaining components affect repair or replacement.'},{title:'“The implant crown came off”',text:'Detachment or fracture requires assessment of bonding or fixation, component damage and chewing forces. Reattachment, repair or replacement may be considered. Keep the detached restoration and bring it to the clinic.'},{title:'“It hurts when I chew” · “The gums bleed”',text:'We assess bite problems, gum inflammation and peri-implantitis. Symptoms alone do not establish a screw problem or inflammation.'},{title:'When repair may not be sufficient',text:'Fixture damage or advanced surrounding tissue damage may require removal, replacement, revision surgery or another option. Implant system compatibility and component availability also affect what is possible.'}],
 care:'Do not tighten components yourself or use household glue. Avoid chewing hard food in the affected area and have the cause examined.',caution:'A loose restoration differs from movement of the fixture. Repair suitability requires examination; retightening alone cannot resolve every fracture or repeated loosening.'},
 'peri-implantitis':{
 definition:'We distinguish inflammation of the soft tissue around an implant from peri-implantitis involving loss of supporting bone.',examination:'Bleeding, pus, tissue probing depth, oral hygiene and necessary imaging are assessed. Earlier examinations, when available, help compare changes and bone condition.',
 steps:['Examine surrounding tissue','Assess inflammation and bone','Hygiene guidance and necessary treatment','Reassess after treatment','Regular maintenance'],
 sections:[{title:'“The gums around my implant bleed”',text:'Bleeding, swelling or discomfort requires gum assessment. Inflammation may occur with little pain, and symptoms alone cannot determine whether bone has been lost.'},{title:'Treatment depends on the extent of damage',text:'Cleaning methods and necessary nonsurgical care are reviewed. Persistent inflammation or bone damage may require assessment for surgery or implant removal.'}],care:'Choose interdental cleaning tools to suit the spaces and restoration. Continue checking inflammation and tissue changes after treatment.',caution:'Inflammation may recur and further treatment may be needed. Smoking, previous periodontal disease and hygiene are considered.',},
 'implant-maintenance':{
 definition:'Ongoing care checks implant and restoration function and the health of surrounding tissues.',examination:'We assess tissues, bleeding, inflammation, bite, screws and restorations. Imaging may be compared when needed.',steps:['Regular examination','Gum care around implants','Check bite, screws and restoration','Assess supporting tissue','Adjust the individual care plan'],
 sections:[{title:'Daily care',text:'Learn brushing and interdental cleaning suited to the restoration. Small spaces and areas beneath restorations that are difficult to clean also need attention.'},{title:'Check-up intervals are individual',text:'Gum health, cleaning ability, previous inflammation and component problems determine intervals. Do not wait for the next routine check if a screw loosens or bleeding occurs.'}],care:'Noting changes in bleeding, odor, looseness and discomfort when chewing can help the examination.',caution:'Regular examinations cannot prevent all complications. New changes need a separate assessment.'},
 'cavity':{
 definition:'Decayed areas are assessed and tooth form and function are restored while preserving remaining tooth tissue where possible.',examination:'We assess decay extent and depth, cracks, remaining tissue and pulp responses, together with pain patterns and necessary radiographs.',steps:['Identify decay','Assess extent and depth','Evaluate remaining tooth tissue','Assess pulp','Consider tooth and pulp preservation','Necessary treatment','Final restoration'],
 sections:[{title:'Composite fillings and inlays/onlays',text:'Damage, position, bonding conditions and chewing forces determine whether direct composite or a made-to-fit inlay/onlay is considered. The restoration needed to protect remaining tissue varies by tooth.'},{title:'Deep decay',text:'Decay close to the pulp requires pulp assessment. Vital pulp therapy (VPT) may be considered if indicated, or root canal treatment may be needed.'},{title:'Extensive tooth damage',text:'After evaluating remaining tissue and whether the tooth can be retained, we discuss composite build-up, partial restorations or prosthetic treatment. Damage size alone does not determine treatment.'}],care:'Brush with fluoride toothpaste, clean between teeth, review diet and decay risk, and regularly check restoration margins.',caution:'Persistent or worsening sensitivity or pain requires reassessment of the pulp and other causes. Deep decay may need further treatment later.'},
 'resin-build-up':{
 definition:'Composite resin restores tooth tissue lost to decay or fracture using the remaining tooth as a foundation.',examination:'We assess the amount and location of remaining tissue, cracks and fractures, pulp, moisture control, bonding and bite.',steps:['Identify tooth damage','Assess remaining tissue','Evaluate restorability','Composite build-up','Check form and bite','Final restoration and follow-up'],
 sections:[{title:'When can it be considered?',text:'Depending on damage and bonding conditions, build-up may serve as a restoration or prepare the shape before prosthetic treatment.',items:['Extensive loss of tooth tissue','A fractured part of a tooth','A lost existing restoration','Need to restore tooth shape','Need to restore shape before prosthetic treatment']},{title:'It is not suitable for every tooth',text:'Deep fractures, root damage, too little tissue or difficulty controlling moisture may require other treatment. A crown or onlay may be considered after build-up.'}],care:'Avoid cracking very hard foods with the tooth. Check restoration margins, fractures and bite.',caution:'Detachment, wear or fracture can occur. Pulp condition may separately require VPT or root canal treatment.'},
 'vital-pulp-therapy':{
 definition:'Vital Pulp Therapy (VPT) aims to preserve healthy living pulp where possible. When decay approaches or exposes the pulp, it is considered only after assessment and when indicated.',examination:'Pain, pulp responses, inflammation and infection, bleeding, remaining tooth tissue, moisture control and the ability to create a sealed restoration are assessed together.',steps:['Remove decay','Check pulp condition','Assess pulp preservation','Treat the necessary part of the pulp','Apply MTA or another suitable material','Restore the tooth','Follow-up'],
 sections:[{title:'What does MTA do?',text:'MTA (Mineral Trioxide Aggregate) or another pulp-treatment material is applied at the appropriate site before restoration. Infection control, a sealed restoration and follow-up matter as well as the material.'},{title:'VPT is not possible for all deep decay',text:'Pulp and tissues around the root, bleeding control and remaining tissue determine the extent of treatment. Examination or findings during treatment may change the plan to root canal treatment.'},{title:'Pulp is checked after treatment',text:'Symptoms and changes in pulp and tissues around the root are monitored. Root canal treatment may still be needed after VPT.'}],care:'Attend scheduled checks for pain, the restoration and any necessary imaging findings.',caution:'Pulp preservation and long-term results cannot be guaranteed. Changes such as continuing spontaneous pain or swelling require reassessment.'},
 'root-canal':{
 definition:'Root canal treatment evaluates the pulp and canals, removes infected or damaged tissue when needed, cleans and disinfects the canals, and fills them.',examination:'We check pain, pulp responses, tissues around the root and imaging. Cracks and remaining tissue help determine whether the tooth can be retained and finally restored.',steps:['Assess pulp and canals','Decide whether treatment is needed','Clean and disinfect canals','Fill canals','Complete final restoration','Follow-up'],
 sections:[{title:'Pulpitis, pulp necrosis and canal infection',text:'Inflamed pulp, loss of pulp vitality and canal infection are distinguished. Pain or its absence alone does not determine whether treatment is needed.'},{title:'Previously treated teeth also need assessment',text:'Pain or a lesion around the root of a previously treated tooth prompts examination of the restoration, canals and cracks. Retreatment or referral may be discussed depending on findings and complexity.'}],care:'Avoid damage while a temporary restoration is in place and complete the final restoration. Check-ups monitor the restoration and tissues around the root.',caution:'Complex canals, reinfection or cracks may require further treatment. Root canal treatment cannot preserve every tooth.'},
 'periodontal':{
 definition:'Periodontal treatment assesses gums and tooth-supporting tissues and treats inflammation, calculus and periodontal pockets.',examination:'Pocket depth, bleeding, calculus, tooth mobility and alveolar bone on necessary images are examined. Hygiene and general health are also reviewed.',steps:['Examine gums','Assess calculus and inflammation','Necessary periodontal treatment','Reassess after treatment','Maintenance'],
 sections:[{title:'Have you noticed these changes?',text:'Examination helps identify the causes of bleeding, swelling, recession and loose teeth.',items:['“My gums bleed when I brush”','“My gums are swollen and painful”','“My gums seem to be receding”','“My teeth are loose”','“A lot of tartar builds up”']},{title:'Scaling and root surface treatment',text:'Plaque and calculus are removed and nonsurgical periodontal care is considered. Persistent pockets or inflammation may require reassessment for periodontal surgery.'},{title:'Reassessment and regular care',text:'Gum and pocket changes guide care intervals. If implants are present, their surrounding tissues are checked too.'}],care:'Continue suitable brushing and interdental cleaning. Smoking and systemic conditions that affect care are considered.',caution:'Sensitivity or changes in gum shape may follow treatment. Treatment does not fully restore all previously damaged supporting tissue.'},
 'scaling':{
 definition:'Scaling removes calculus and plaque from tooth surfaces and around the gums.',examination:'We assess calculus deposits, bleeding, inflammation, pockets and sensitivity.',steps:['Examine teeth and gums','Remove calculus and plaque','Check gums','Assess need for further care','Hygiene care'],sections:[{title:'Is scaling enough?',text:'Deep pockets or advanced periodontal disease may require further treatment such as root surface instrumentation.'},{title:'Care intervals',text:'Intervals depend on calculus formation, gum health and oral hygiene.'}],care:'Discuss sensitivity and include interdental cleaning in daily care.',caution:'Temporary sensitivity or discomfort can occur. Continuing bleeding or pain needs reassessment.'},
 'prosthodontics':{
 definition:'Restorations replace or repair tooth form, function and, where needed, appearance after damage or tooth loss.',examination:'Remaining tissue, pulp and gums, missing-tooth spaces and adjacent teeth, bite and bonding conditions are assessed.',steps:['Examine teeth and bite','Plan tissue preservation and restoration extent','Necessary preparation','Make and check restoration','Fit or bond','Follow-up'],sections:[{title:'Choosing the extent of restoration',text:'Crowns cover teeth, while inlays/onlays restore part of the tooth according to damage. Conventional bridges connect an artificial tooth to adjacent supporting teeth. Tissue removal and protection of remaining teeth are considered together.'},{title:'Adhesive and aesthetic restorations',text:'Veneers and Maryland bridges require assessment of tooth and restoration bonding conditions. No-preparation or minimal-preparation approaches depend on tooth shape, arrangement and bite.'},{title:'Zirconia restorations',text:'Zirconia is one possible material for crowns and bridges and, when indicated, veneers and inlays/onlays. Restoration type, thickness, surface treatment and bonding system are planned together.'}],care:'Clean margins and under bridges; regularly check bite, detachment and fractures.',caution:'Sensitivity, detachment, fracture or further pulp treatment may occur. No material or method is superior in every situation.'},
 'zirconia-inlay-onlay':{
 definition:'An inlay restores damage within a tooth; an onlay can also cover affected chewing cusps. Zirconia is one material that may be considered for these partial restorations.',examination:'Remaining tissue, cusp strength, pulp, required thickness, bite, moisture control and bonding feasibility are assessed.',steps:['Assess damage','Plan tissue preservation and restoration extent','Review material and thickness','Make restoration','Prepare surfaces and bond','Check bite and follow-up'],sections:[{title:'Material is chosen for the tooth condition',text:'Composite, other inlay/onlay materials and crowns are compared. Zirconia partial restorations are not appropriate for every damaged tooth.'},{title:'Surface treatment and bonding',text:'Both restoration and tooth-side conditions are reviewed. STM may be considered where applicable, according to the material, manufacturing stage and bonding system.'}],care:'Check margins and bite and keep spaces between teeth clean.',caution:'Detachment, fracture, sensitivity or additional pulp treatment may occur. Material alone cannot guarantee longevity or results.'},
 'laminate':{
 definition:'Veneers are thin restorations bonded to tooth surfaces to improve color, shape or size.',examination:'We assess arrangement, protrusion, desired color change, tooth surfaces and remaining enamel, restoration thickness and bite.',steps:['Assess shape, color and bite','Compare options','Assess preparation required','Make veneers','Check fit and bond','Care and follow-up'],sections:[{title:'When no or minimal preparation is possible',text:'Tooth shape, arrangement, protrusion, color change and required thickness determine suitability for no or minimal preparation. No-preparation veneers are not possible for everyone.'},{title:'Other options are considered',text:'Orthodontics may suit position changes, whitening may address discoloration, and composite may restore small defects.'},{title:'Zirconia veneers and bonding',text:'Material, thickness, tooth-side bonding and restoration surface preparation are reviewed together. STM is one part of bonding and does not guarantee the result.'}],care:'Avoid biting hard objects with front teeth. Check margins and bite; discuss grinding or clenching.',caution:'Tooth preparation is irreversible. Detachment, fracture, color differences and sensitivity are possible.'},
 'maryland-bridge':{
 definition:'A Maryland bridge (resin-bonded bridge) replaces a missing tooth using wings or other structures bonded to neighboring teeth to support an artificial tooth.',examination:'The gap, enamel and restorations of adjacent teeth, periodontal health, bite, bonding surface and cleaning access are assessed.',steps:['Examine gap and adjacent teeth','Compare options','Plan support and bonding','Make bridge','Bond and check bite','Maintenance'],sections:[{title:'Different from a conventional bridge',text:'A conventional bridge connects an artificial tooth to crowns covering adjacent supports. A Maryland bridge usually bonds to the inner tooth surfaces. The number of supports and wing design vary by case.'},{title:'Compare with implants and conventional bridges',text:'Adjacent teeth, bone, gums, bite and suitability for surgery influence selection. No option is better for every patient.'},{title:'Preparing the bonding surface',text:'Surface treatment and bonding are selected for the material. With zirconia, suitability of STM is also assessed according to material conditions.'}],care:'Clean beneath the artificial tooth and around bonded supports. Stop using it and get checked if lifting or detachment occurs.',caution:'Debonding or fracture may occur. Reattachment requires assessment of the tooth and restoration.'},
 'stm':{
 definition:'Here STM means Surface Transition Machine. It treats the bonding surface of zirconia or another compatible restoration to modify surface characteristics needed for bonding.',examination:'Restoration material, manufacturing stage, suitable surface treatments, tooth-side conditions and bonding system compatibility are reviewed.',steps:['Zirconia restoration','STM surface treatment','Microscopic surface changes','Prepare surface for bonding','Bond using a suitable system'],sections:[{title:'One part of the bonding process',text:'Surface modification is part of preparation. Tooth preparation, moisture control, primers, cement and restoration shape also matter.'},{title:'Related treatments',text:'It may be considered for zirconia veneers, no/minimal-preparation veneers, Maryland bridges, zirconia inlays/onlays and other adhesive restorations. The same treatment is not applied to every material or restoration.'},{title:'Laboratory and clinical results differ',text:'Published STM research includes laboratory tests on zirconia specimens. Bond-strength findings cannot be directly interpreted as long-term patient outcomes. Specific numbers or manufacturer claims do not guarantee treatment results.'}],care:'Regularly check margins, bite, detachment and fracture after bonding.',caution:'Equipment and surface treatment alone cannot guarantee long-term bonding or retention. Application depends on the material and clinical assessment.'},
 'whitening':{
 definition:'Whitening changes the color of natural teeth. Methods and response depend on the cause of discoloration and oral health.',examination:'We check discoloration causes, decay, gums, sensitivity and existing composite, crowns and veneers.',steps:['Assess discoloration','Check decay and gums','Review restorations','Check sensitivity','Whitening','Aftercare'],sections:[{title:'Existing restorations differ from natural teeth',text:'Crowns, veneers and composite may respond differently to whitening. Possible color mismatch and restoration needs should be discussed.'},{title:'Changes and duration vary',text:'Discoloration, tooth condition and habits affect response and how long changes last. Desired color and treatment scope are discussed during care.'}],care:'Follow the provided use and care instructions and monitor color and sensitivity.',caution:'Temporary sensitivity or gum irritation can occur. The degree or duration of whitening cannot be guaranteed uniformly.'},
 'wisdom-teeth':{
 definition:'Wisdom-tooth eruption, decay, inflammation and surrounding structures are assessed to decide whether monitoring or extraction is appropriate.',examination:'Erupted, partially erupted and impacted teeth are distinguished. Inflammation, decay and relationships to nearby teeth are checked. Imaging may assess nerve canals and other structures.',steps:['Examination','Locate wisdom tooth','Assess extraction need','Assess complexity and surrounding structures','Extract if indicated','Aftercare'],sections:[{title:'Must every wisdom tooth be removed?',text:'Problem-free teeth that can be kept clean may be monitored. Repeated inflammation, decay and effects on adjacent teeth inform the decision.'},{title:'Complexity may require referral',text:'Cases beyond the clinic’s treatment scope may be referred to an appropriate medical institution.'}],care:'Follow instructions for bleeding control, eating and hygiene, and attend healing checks.',caution:'Bleeding, swelling, infection or altered sensation can occur. Seek professional advice for persistent severe pain or bleeding.'},
 'temporomandibular-disorders':{
 definition:'Temporomandibular Disorders (TMD) include various joint and chewing-muscle conditions. Joint sounds alone do not establish a disorder or treatment need.',examination:'We assess pain, opening range, jaw movement, sounds, muscle pain and tension, grinding or clenching, teeth and bite. Imaging may be considered when needed.',steps:['Review symptoms and habits','Examine joints and muscles','Further assessment if needed','Plan conservative care','Reassess progress'],sections:[{title:'Symptoms we check',text:'We ask where discomfort occurs, when it started and how movement changes it.',items:['“My jaw hurts when I open my mouth”','“My jaw makes sounds”','“I cannot open well”','“Chewing feels uncomfortable”','“My jaw or facial muscles ache in the morning”','“I think I clench my teeth”']},{title:'Conservative care after diagnosis',text:'General options may include habit changes, conservative care, medicines, physical therapy or a stabilization splint. Confirm the services actually provided here during consultation; referral may be needed.'}],care:'Review habits that strain the jaw and adjust diet and daily activities as advised. Do not forcibly manipulate or excessively open the jaw.',caution:'Course and treatment depend on the cause. Treatments permanently changing teeth or bite require careful assessment of necessity and alternatives.'},
 'partial-orthodontics':{
 definition:'Limited orthodontics aims to improve the position and arrangement of certain teeth or an area rather than the whole dentition. It describes treatment scope.',examination:'The overall bite, skeletal relationship, gums, alveolar bone, available space and required movement are assessed.',steps:['Assess overall bite and periodontal health','Assess limited movement','Plan scope and appliance','Move teeth in stages','Check bite','Retention and care'],sections:[{title:'Situations that may be considered',text:'Overall assessment determines whether limited movement can meet the goal.',items:['Aligning some front teeth','Spaces between particular teeth','Tilting of some teeth','Limited tooth movement','Tooth positioning before restorations when needed']},{title:'The whole bite still matters',text:'General bite or skeletal problems may make limited treatment unsuitable. Comprehensive orthodontics or another treatment may be needed.'},{title:'Limited treatment and clear aligners differ',text:'Limited orthodontics describes scope; clear aligners describe an appliance method. Appliance selection depends on movement goals and suitability.'}],care:'Clean teeth and appliances and follow retainer and check-up instructions after treatment.',caution:'Relapse and gum or root changes can occur. Scope and duration are confirmed after examination.'},
 'clear-aligners':{
 definition:'Clear Aligner Therapy moves teeth through a sequence of transparent appliances made for the individual teeth.',examination:'Dentition, bite, periodontal health, movement type and extent, and ability to wear appliances as instructed are assessed.',steps:['Examine teeth and bite','Plan movement','Make appliances','Wear and check in stages','Adjust plan if needed','Retention and care'],sections:[{title:'Clear aligners describe an appliance',text:'Limited or comprehensive treatment scope is separate from appliance type. Transparent appliances do not suit every movement or bite problem.'},{title:'Wear and checks matter',text:'Follow clinician instructions for wear and replacement and check tooth movement and appliance fit. Additional procedures or appliances may be needed.'}],care:'Keep teeth and appliances clean and use retainers as instructed after treatment.',caution:'Movement response, wear and bite may change duration or the plan. Appliance type alone cannot guarantee the desired result.'},
 'diastema':{
 definition:'Diastema means a space between teeth. Treatment depends on causes such as tooth size, position and gum health.',examination:'We check gap size and position, tooth shape and arrangement, bite, gums and supporting tissue. A recently enlarging gap also needs cause assessment.',steps:['Identify the gap','Assess causes and current condition','Consider movement or shape restoration','Compare options','Chosen treatment','Check bite and maintenance'],sections:[{title:'When teeth need repositioning',text:'Limited orthodontics or clear aligners may be considered. The overall bite may require broader orthodontic treatment.'},{title:'When restoring tooth shape is suitable',text:'Composite space closure may be considered according to tooth width and shape, bonding and bite.'},{title:'When shape and color both need changes',text:'Veneers or other aesthetic restorations may be considered, comparing preparation and other options.'},{title:'One method does not suit everyone',text:'Causes and periodontal health are checked first, distinguishing movement from shape restoration. Combined treatment or gum treatment first may be needed.'}],care:'Care for retainers, restoration margins and bite according to treatment and monitor changes in the gap.',caution:'Spaces may recur after orthodontics; restorations can detach or fracture. Causes and care requirements should be assessed before treatment.'},
};
